# Numpy Arrays

### Example: Lists vs. NumPy Arrays

In [1]:
import numpy as np

# Python list
list_data = [1, 2, 3, 4]
list_sum = sum(list_data)  # Slow for large data

# NumPy array
np_data = np.array([1, 2, 3, 4])
np_sum = np.sum(np_data)   # Optimized C backend

print(list_sum)
print(np_sum)

10
10


### 2. Creating and Manipulating Arrays
#### 2.1 Array Creation
NumPy arrays can be created from lists or using built-in functions

In [2]:
# 1D Array
arr1d = np.array([1, 2, 3])  

# 2D Array (Matrix)
arr2d = np.array([[1, 2], [3, 4]])  

# Special Arrays
zeros = np.zeros(3)        # [0., 0., 0.]  
ones = np.ones((2, 2))     # [[1., 1.], [1., 1.]]  
range_arr = np.arange(5)   # [0, 1, 2, 3, 4] 
space_arr = np.linspace(0, 1, 5) # [0., 0.25, 0.5, 0.75, 1.]

print(arr1d)
print(arr2d)
print(zeros)
print(ones)
print(range_arr)
print(space_arr)

[1 2 3]
[[1 2]
 [3 4]]
[0. 0. 0.]
[[1. 1.]
 [1. 1.]]
[0 1 2 3 4]
[0.   0.25 0.5  0.75 1.  ]


##### 2.1.2 Key Properties 

In [3]:
print(arr1d.shape)    # Dimensions
print(arr1d.dtype)    # Data type (e.g., int64, float32)

print(arr2d.shape)    # Dimensions
print(arr2d.dtype)    # Data type (e.g., int64, float32)

print(zeros.shape)    # Dimensions
print(zeros.dtype)    # Data type (e.g., int64, float32)

print(ones.shape)    # Dimensions
print(ones.dtype)    # Data type (e.g., int64, float32)

print(range_arr.shape)    # Dimensions
print(range_arr.dtype)    # Data type (e.g., int64, float32)

print(space_arr.shape)    # Dimensions
print(space_arr.dtype)    # Data type (e.g., int64, float32)

(3,)
int64
(2, 2)
int64
(3,)
float64
(2, 2)
float64
(5,)
int64
(5,)
float64


#### 2.2 Indexing and Slicing
##### 1D Arrays (Like Python Lists):

In [4]:
arr = np.array([10, 20, 30, 40])
print(arr[0])      # 10  
print(arr[1:3])     # [20, 30]  

10
[20 30]


##### 2D Arrays (Row, Column Format):

In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[0, 1])    # 2 (Row 0, Column 1)  
print(matrix[:, 1])    # [2, 5] (All rows, Column 1)  

2
[2 5]


##### Boolean Indexing/Masking:

In [6]:
arr = np.array([1, 2, 3, 4])
print(arr[arr > 2])    # [3, 4]  

[3 4]


### 3. Mathematical Operations
#### 3.1 Vectorized Operations
NumPy eliminates the need for loops:

In [7]:
arr = np.array([1, 2, 3])
print(arr * 2)          # [2, 4, 6]  
print(arr + arr)        # [2, 4, 6]  
print(np.sqrt(arr))     # [1., 1.414, 1.732]  

[2 4 6]
[2 4 6]
[1.         1.41421356 1.73205081]


#### 3.2 Broadcasting in NumPy

Broadcasting is NumPy's powerful mechanism for performing element-wise operations between arrays of different shapes without explicitly expanding them in memory. It follows strict rules to determine compatibility

---

##### **Key Rules of Broadcasting**  
**Trailing Dimensions Must Match**:  
   - NumPy compares shapes from the **rightmost dimension** backward.  
   - Two dimensions are compatible if:  
     - They are **equal**, or  
     - One of them is **1** (and can be stretched to match).

Broadcasting:

```python
arr + 5  # Adds 5 to each element
arr * 2  # Multiplies each element by 2
``

**Example 1: Vector + Scalar**  

In [8]:
arr = np.array([1, 2, 3])
arr = arr + 5  # Scalar 5 is broadcast to [5, 5, 5]  
# Creates a new array: [1+5, 2+5, 3+5] = [6, 7, 8]

print(arr)


[6 7 8]


**Example 2: Matrix + Vector (Row-wise)**  

In [ ]:
matrix = np.ones((3, 3))  # Shape (3, 3)
print(matrix)
vector = np.array([1, 2, 3])  # Shape (3,)
print(vector)

mat_vet = matrix + vector  # Vector broadcast to [[1,2,3], [1,2,3], [1,2,3]]
print(mat_vet)
   

**Why is this possible?**  
   - `(3, 3)` + `(3,)` → NumPy aligns trailing dimension (`3` == `3`).  
   - The vector is implicitly treated as a row (shape `(1, 3)`) and **repeated** for all rows.  


**Example 3: Incompatible Shapes**  

In [ ]:
matrix = np.ones((3, 3))
print(matrix)
vector = np.array([1, 2])  # Shape (2,)
print(vector)

try:
    mat_vet = matrix + vector  # This will raise a ValueError
    print(mat_vet)
except ValueError as e:
    print(f"Broadcasting failed: {e}")

**Error**: `ValueError: operands could not be broadcast together with shapes (3,3) (2,)`  
**Reason**: Trailing dimensions (`3` vs `2`) do not match. 

#### **Explicit Broadcasting with `np.newaxis`**  
If automatic broadcasting fails, reshape arrays manually:  

In [ ]:
matrix = np.ones((3, 3))  # Shape (3, 3)
print(matrix)
vector = np.array([1, 2, 3])  # Shape (3,)
print(vector)
vector = vector[:, np.newaxis]  # Reshape to (3, 1)
mat_vet = matrix + vector  # Now broadcasts column-wise
print(mat_vet)


### 4. Practical Exercises
#### Exercise 1: Statistical Calculations

##### Dataset:

```python
data = np.array([22, 45, 34, 19, 28])  
```

##### Tasks:

- Compute mean, median, and standard deviation.

- Normalize the data to a 0–1 scale.

##### Solutions:

In [ ]:
data = np.array([22, 45, 34, 19, 28]) 

mean = np.mean(data)  
median = np.median(data)  
std = np.std(data)  
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))  

print(mean)
print(median)
print(std)
print(normalized)

Normalizing data to a 0–1 scale means transforming the values so that they fall within the range [0, 1]. This is a common preprocessing step in data analysis and machine learning to ensure that all features are on a similar scale, which can improve the performance of certain algorithms (e.g., gradient descent in neural networks, distance-based methods like k-NN).

##### Theory Behind Min-Max Normalization (0–1 Scaling)
The most common way to normalize data to a 0–1 scale is using **min-max normalization**. The formula is:

$$
x_{\text{normalized}} = \frac{x - \min(X)}{\max(X) - \min(X)}
$$

Where:
- $x$ = original value
- $\min(X)$ = minimum value in the dataset
- $\max(X)$ = maximum value in the dataset
  
##### Steps to Normalize Data
Given data:  
`data = np.array([22, 45, 34, 19, 28])`

1. **Find the min and max**:
   - $ \min(X) = 19 $
   - $ \max(X) = 45 $

2. **Apply the formula**:
   - For $ x = 22 $:  
     $ \frac{22 - 19}{45 - 19} = \frac{3}{26} \approx 0.115 $
   - For $ x = 45 $:  
     $ \frac{45 - 19}{45 - 19} = \frac{26}{26} = 1.0 $
   - For $ x = 34 $:  
     $ \frac{34 - 19}{45 - 19} = \frac{15}{26} \approx 0.577 $
   - For $ x = 19 $:  
     $ \frac{19 - 19}{45 - 19} = \frac{0}{26} = 0.0 $
   - For $ x = 28 $:  
     $ \frac{28 - 19}{45 - 19} = \frac{9}{26} \approx 0.346 $

3. **Result**:  
   The normalized array is approximately:  
   `[0.115, 1.0, 0.577, 0.0, 0.346]`

##### Key Points
- **Purpose**: Ensures all values are on a consistent scale (0–1).
- **When to Use**: Useful when the absolute scale of the data doesn't matter, but relative differences do (e.g., in neural networks, clustering, or distance-based algorithms).
- **Alternative Normalization**: If outliers are present, other methods like **Z-score standardization** (scaling to mean 0, std 1) may be better.

#### Exercise 2. Normalizing a Dataset (Column-wise) Using Broadcasting:

In [ ]:
data = np.random.rand(5, 3)  # 5 samples, 3 features
print(data)
mean = data.mean(axis=0)  # Shape (3,)
print(mean)
data -= mean  # Broadcasts mean across all rows
print(data) 

#### Exercise 3: Reshaping & Transposing

Given:

``python
matrix = np.arange(1, 10).reshape(3, 3)  # [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
``

##### Tasks:

- Reshape it into a 1x9 array.

- Transpose the matrix (swap rows & columns).

In [ ]:
matrix = np.arange(1, 10).reshape(3, 3)  # [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matrix)
reshaped = matrix.reshape(1, 9)  # [[1, 2, 3, 4, 5, 6, 7, 8, 9]]
print(reshaped)
transposed = matrix.T            # [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
print(transposed)

Challenges
- Generate an array of random data using numpy
np.random.seed(42)  
random_data = np.random.rand(5, 5) 

- Create a 3x3 identity matrix using np.eye() and extract its second row.
- Given temps = np.array([68, 72, 65, 70]), convert Fahrenheit to Celsius:
C = (F - 32) * 5/9


Hands-On Challenges (60 min)
A. Statistical Analysis (30 min)
Dataset:

python
sales = np.random.randint(100, 1000, size=(4, 12))  # 4 years, 12 months
Tasks:

Find mean, median, and std deviation for annual sales.

Which month had the highest sales across all years?

Reshaping & Transposing (30 min)
Challenge:

Load the following 1D array into a 3x3 matrix and compute its transpose:

python
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
Advanced: Normalize each column to 0-1 range.

Solution:

python
matrix = data.reshape(3, 3)
normalized = (matrix - np.min(matrix, axis=0)) / (np.max(matrix, axis=0) - np.min(matrix, axis=0))

**Objective:** Use NumPy to analyze real-world datasets (temperatures, stock prices, images).  

---

## **1. Real-World Dataset 1: Temperature Analysis**  
**Dataset:** Monthly average temperatures (in °C) for a city over 2 years.  
```python
import numpy as np
temps = np.array([
    [10, 12, 15, 20, 25, 30, 32, 31, 28, 22, 16, 11],  # Year 1
    [9, 11, 14, 19, 24, 29, 31, 32, 27, 21, 15, 10]    # Year 2
])
```

### **Exercises:**  
1. **Annual Averages:**  
   ```python
   np.mean(temps, axis=1)  # [20.25, 19.75]
   ```
2. **Hottest Month (Across Years):**  
   ```python
   np.argmax(np.mean(temps, axis=0)) + 1  # July (Month 7)
   ```
3. **Temperature Fluctuations (Std Dev):**  
   ```python
   np.std(temps)  # 7.48°C
   ```

---

## **2. Real-World Dataset 2: Stock Price Analysis**  
**Dataset:** Daily closing prices (in USD) of a stock for 5 days.  
```python
prices = np.array([145.3, 147.8, 146.2, 150.1, 149.5])
```

### **Exercises:**  
1. **Daily Returns (% Change):**  
   ```python
   returns = np.diff(prices) / prices[:-1] * 100
   # [1.72%, -1.08%, 2.67%, -0.4%]
   ```
2. **Volatility (Std Dev of Returns):**  
   ```python
   np.std(returns)  # 1.54%
   ```
3. **Moving Average (3-Day Window):**  
   ```python
   np.convolve(prices, np.ones(3)/3, mode='valid')
   # [146.43, 148.03, 148.6]
   ```

---

## **3. Real-World Dataset 3: Image Processing**  
**Concept:** Grayscale images are 2D NumPy arrays (0=black, 255=white).  

### **Example: Invert an Image**  
```python
from PIL import Image
import matplotlib.pyplot as plt

# Load a sample image (convert to grayscale)
img = Image.open("path/to/image.jpg").convert('L')
img_array = np.array(img)

# Invert colors
inverted = 255 - img_array

# Plot
plt.imshow(inverted, cmap='gray')
```

### **Exercises:**  
1. **Crop the Image:**  
   ```python
   cropped = img_array[50:150, 100:200]  # Height × Width
   ```
2. **Brighten by 20%:**  
   ```python
   brightened = np.clip(img_array * 1.2, 0, 255).astype(np.uint8)
   ```

---

## **4. Real-World Dataset 4: Sensor Data**  
**Dataset:** Accelerometer readings (X, Y, Z axes) from a smartphone.  
```python
sensor_data = np.array([
    [0.12, 0.98, 0.04],  # Sample 1
    [0.23, 1.02, 0.05],  # Sample 2
    [0.08, 0.95, 0.03]   # Sample 3
])
```

### **Exercises:**  
1. **Magnitude of Acceleration:**  
   ```python
   magnitudes = np.sqrt(np.sum(sensor_data**2, axis=1))
   ```
2. **Detect Motion (Threshold >1.0):**  
   ```python
   motion = magnitudes[magnitudes > 1.0]
   ```

---

## **5. Real-World Dataset 5: Population Demographics**  
**Dataset:** Population (in millions) of 3 countries over 5 years.  
```python
population = np.array([
    [142, 144, 146, 148, 150],  # Country A
    [67, 68, 69, 70, 71],        # Country B
    [83, 84, 85, 86, 87]         # Country C
])
```

### **Exercises:**  
1. **Annual Global Population:**  
   ```python
   np.sum(population, axis=0)  # [292, 296, 300, 304, 308]
   ```
2. **Fastest-Growing Country:**  
   ```python
   growth_rates = np.diff(population) / population[:, :-1] * 100
   np.argmax(np.mean(growth_rates, axis=1))  # Country A (1.41% avg)
   ```
## **Homework Assignment**  
**Dataset:** Daily COVID-19 cases (5-day sample).  
```python
cases = np.array([120, 145, 160, 180, 210])
```
**Tasks:**  
1. Compute the 5-day moving average.  
2. Find days with cases >150.  

**Solution:**  
```python
moving_avg = np.convolve(cases, np.ones(3)/3, mode='valid')  # [141.67, 161.67, 183.33]
high_cases = cases[cases > 150]  # [160, 180, 210]
```

---


# **NumPy for Medical Data Analysis**  
**Objective:** Process and analyze medical datasets (vital signs, MRI scans, genomic data) using NumPy.  

---

## **1. Patient Vital Signs Analysis**  
**Dataset:** Heart rate (bpm) and blood pressure (mmHg) for 5 patients.  
```python
import numpy as np
vital_signs = np.array([
    [72, 120, 80],  # Patient 1: HR, SBP, DBP
    [68, 115, 76],
    [88, 145, 90],  # Patient 3 (hypertensive)
    [76, 130, 85],
    [94, 110, 70]   # Patient 5 (tachycardic)
])
```

### **Exercises:**  
1. **Identify Hypertensive Patients (SBP >140 or DBP >90):**  
   ```python
   hypertensive = vital_signs[(vital_signs[:,1] > 140) | (vital_signs[:,2] > 90)]
   # Returns Patient 3's data
   ```
2. **Calculate Mean Arterial Pressure (MAP):**  
   ```python
   MAP = vital_signs[:,2] + 0.33*(vital_signs[:,1] - vital_signs[:,2])
   ```

---

## **2. Medical Imaging (MRI Slice Processing)**  
**Concept:** MRI scans are 3D NumPy arrays (height × width × slices).  

### **Example: Tumor Segmentation**  
```python
# Simulated MRI slice (0=black, 1=white matter, 2=tumor)
mri_slice = np.array([
    [0, 0, 1, 1, 0],
    [0, 2, 1, 2, 0],
    [0, 0, 2, 0, 0]
])

# Count tumor pixels
tumor_pixels = np.sum(mri_slice == 2)  # 3 pixels
```

### **Exercise:**  
1. **Calculate Tumor Area %:**  
   ```python
   tumor_area_pct = 100 * tumor_pixels / mri_slice.size  # 20%
   ```

---

## **3. Genomic Data (DNA Sequences)**  
**Dataset:** DNA base pairs (A=0, T=1, C=2, G=3) for 3 patients.  
```python
dna_sequences = np.array([
    [0, 1, 2, 3, 0, 1],  # Patient 1: A-T-C-G-A-T
    [2, 2, 0, 1, 3, 0],  # Patient 2: C-C-A-T-G-A
    [3, 1, 1, 0, 2, 2]   # Patient 3: G-T-T-A-C-C
])
```

### **Exercises:**  
1. **Find Most Frequent Base at Position 3:**  
   ```python
   from scipy.stats import mode
   mode(dna_sequences[:, 3])  # ModeResult(mode=1 (T), count=2)
   ```
2. **Calculate GC Content (% G or C bases):**  
   ```python
   gc_content = 100 * np.isin(dna_sequences, [2,3]).sum(axis=1) / dna_sequences.shape[1]
   # [33.3%, 50%, 50%]
   ```

---

## **4. Clinical Trial Data**  
**Dataset:** Drug trial results (placebo vs. treatment group).  
```python
# Cholesterol levels (mg/dL) before/after treatment
placebo = np.array([210, 205, 198, 215, 220])  # Before
treatment = np.array([200, 190, 185, 195, 180])  # After
```

### **Exercises:**  
1. **Mean Reduction in Cholesterol:**  
   ```python
   reduction = np.mean(placebo) - np.mean(treatment)  # 23 mg/dL
   ```
2. **Statistical Significance (T-test):**  
   ```python
   from scipy.stats import ttest_ind
   tstat, pval = ttest_ind(placebo, treatment)  # pval < 0.05?
   ```

---

## **5. ECG Signal Processing**  
**Dataset:** Simulated ECG waveform (voltage over time).  
```python
time = np.linspace(0, 5, 1000)  # 5 seconds
ecg = np.sin(2 * np.pi * 1.2 * time) + 0.5 * np.random.randn(1000)  # Noise added
```

### **Exercises:**  
1. **Detect Heartbeats (Peaks >2 Std Devs):**  
   ```python
   peaks = ecg[ecg > np.mean(ecg) + 2*np.std(ecg)]
   ```
2. **Heart Rate (BPM):**  
   ```python
   peak_indices = np.where(ecg > np.mean(ecg) + 2*np.std(ecg))[0]
   bpm = 60 / (np.mean(np.diff(peak_indices)) * (5/1000))  # Convert to BPM
   ```

---

## **Key Medical Takeaways**  
- **Vital Signs:** Boolean indexing for patient triage.  
- **Imaging:** Array math for tumor analysis.  
- **Genomics:** `np.isin()` for sequence patterns.  
- **Trials:** Statistical operations with SciPy.  
- **ECGs:** Signal processing with `np.where()`.  

---

## **Homework: Diabetes Dataset**  
**Dataset:** Fasting glucose (mg/dL) for 10 patients:  
```python
glucose = np.array([92, 104, 88, 150, 132, 115, 98, 167, 120, 142])
```
**Tasks:**  
1. Classify patients as diabetic (>126 mg/dL).  
2. Calculate interquartile range (IQR).  

**Solution:**  
```python
diabetic = glucose[glucose > 126]             # [150, 132, 167, 142]
q75, q25 = np.percentile(glucose, [75, 25])  
iqr = q75 - q25                              # 34.5 mg/dL
```

---

In [1]:
import numpy as np
vital_signs = np.array([
    [72, 120, 80],  # Patient 1: HR, SBP, DBP
    [68, 115, 76],
    [88, 145, 90],  # Patient 3 (hypertensive)
    [76, 130, 85],
    [94, 110, 70]   # Patient 5 (tachycardic)
])

hypertensive = vital_signs[(vital_signs[:,1] > 140) | (vital_signs[:,2] > 90)] # Returns Patient 3's data
   
MAP = vital_signs[:,2] + 0.33*(vital_signs[:,1] - vital_signs[:,2])

print(hypertensive)
print(MAP)

[[ 88 145  90]]
[ 93.2   88.87 108.15  99.85  83.2 ]


Hypertensive Patients (by index): [3]
Mean Arterial Pressure (MAP) for each patient: [ 93.33333333  89.         108.33333333 100.          83.33333333]